# Generated by Django 3.2.8 on 2021-10-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('paciente', 'Paciente')], max_length=20),
        ),
    ]
