# Generated by Django 3.2.8 on 2021-10-28 16:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('list_appointments', '0002_auto_20211025_2117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='RolesUser',
        ),
    ]
