# Generated by Django 3.2.8 on 2021-11-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_appointments', '0003_rename_customuser_rolesuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provider', models.SmallIntegerField()),
                ('id_secction', models.CharField(choices=[('SECTION_ONE', 'Section one'), ('SECTION_TWO', 'Section two'), ('SECTION_THREE', 'Section three'), ('SECTION_FOUR', 'Section four')], max_length=100)),
                ('configurations', models.JSONField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
